### ISSUE TITLE
IntelliSense Color

### ISSUE THREAD

**Issue by theshook** [rubjo/ultimate-dark-neo-vs-code#1]
Hello everyone, thank you for this wonderful vscode theme.
I notice something, with autocomplete/suggestion when typing in vscode. Kindly refer to the attached image
![image](https://user-images.githubusercontent.com/33286537/150357546-e01a03e1-f7e6-4953-8da6-049fd3d8a398.png)

I think it would be nice if we can also read the description of autocomplete. Thank you!

**Comment by rubjo** [comment]
Hi, thanks for using the theme. Fixed version on its way out!
