### ISSUE TITLE
Better selected item background color and hover feedback in the sidebar 

### ISSUE THREAD

**Issue by jvzaniolo** [rubjo/ultimate-dark-neo-vs-code#2]
## Current
This color makes it really hard to see the icons from Material Icons. What do you think of adding opacity to it or maybe doing a gray-ish with borders? Also, it doesn't give feedback when hovering.

![CleanShot 2022-02-03 at 2 11 33@2x](https://user-images.githubusercontent.com/54036572/152393350-101775c1-fbf0-41d8-821b-42c92d7b2d2f.png)

### Dracula
![CleanShot 2022-02-03 at 2 05 35@2x](https://user-images.githubusercontent.com/54036572/152392286-97f03cc4-6f1e-44ed-a61a-8e6adc9f9885.png)

### Github Dark
![CleanShot 2022-02-03 at 2 07 25@2x](https://user-images.githubusercontent.com/54036572/152392550-4a6f05a4-5b3a-4716-817b-c6a45f08b7e2.png)

### Monokai Pro
![CleanShot 2022-02-03 at 2 08 24@2x](https://user-images.githubusercontent.com/54036572/152392710-65390e08-4cf8-4697-896d-d345d3465e65.png)

**Comment by rubjo** [comment]
Absolutely, will fix. That colour doesn't really go well there. :) Give me a day or two.

To be honest, there are probably other places where the VS Code theme needs to be refined, as it is more or less a direct port from a Sublime Text theme (which is what I use daily). Thanks for the input!

**Comment by rubjo** [comment]
Please update the theme extension for updated colours. And feel free to suggest more tuning :)
