### ISSUE TITLE
Menu backgrounds are red (#ff0000)

### ISSUE THREAD

**Issue by pjturpeau** [rubjo/ultimate-dark-neo-vs-code#3]
vscode 1.64.2
Ultimate Dark Neo package updated on 2022-02-04 (version specification gives v0.0 - I supposes it's not set correctly in manifest)

I suppose it comes from those following lines in color-theme.json

        "menu.background": "#ff0000",
        "menu.selectionBackground": "#ff0000",

It hurts my eyes :)

Great theme however, I like it with Victor Mono, thank you.

![red-menu](https://user-images.githubusercontent.com/36211072/155625246-8232e542-9ef0-4926-a6d1-9e714175aa2e.png)

**Comment by rubjo** [comment]
Sorry about this. Using macOS, this didn't catch my attention until now. Thanks for letting me know! :)

**Comment by pjturpeau** [comment]
Thank you for the fix! Le 25 févr. 2022 07:43, rubjo ***@***.***> a écrit :
Sorry about this. Using macOS, this didn't catch my attention until now. Thanks for letting me know! :)
