### ISSUE TITLE
Is it possible to add this theme to Visual Studio

### ISSUE THREAD

**Issue by taoning2014** [rubjo/ultimate-dark-neo-vs-code#4]
I recently started dev on C# using Visual Studio and noticed there is no good support for the italics. I wish this amazing theme can be applied to Visual Studio.

**Comment by rubjo** [comment]
Thanks, I have no experience with Visual Studio myself. A quick search suggests that its editor doesn’t support italics. You should probably ask a Visual Studio user / somewhere on a forum dedicated to that software.
