### ISSUE TITLE
As of vscode 1.88.1 squiggles are offset too high.

### ISSUE THREAD

**Issue by magoocas** [rubjo/ultimate-dark-neo-vs-code#5]
![image](https://github.com/rubjo/ultimate-dark-neo-vs-code/assets/596234/47950895-d898-4e59-968f-029990960668)

Just started happening as of the latest version of vscode.

I've tried other themes and couldn't replicate the problem, also reverting to 1.87.2 fixes the issue.

Here's how it looks with the default dark theme in 1.88.1

![image](https://github.com/rubjo/ultimate-dark-neo-vs-code/assets/596234/2ac0c93b-f4f9-40e6-8041-5549b7d72d1e)

**Comment by rubjo** [comment]
Looks like https://github.com/microsoft/vscode/issues/209614
